# Import Required Packages

In [1]:
import warnings
warnings.filterwarnings('ignore')
from bs4 import BeautifulSoup
import pandas as pd

## Scrapping the details

In [2]:
# This function, read a number of movies from a url html string. The default value is 50
def read_m_from_html_string(url, num_of_m=50):
    
    print(url)
    
    with open('TopVoted_500_Movies_HTML.txt', 'r', encoding="utf8") as file:
        html_string = file.read()   # to read the hmtl file as a string
        # I have included the Movies 500 HTML String.txt file in the project folder. Please take a look.
    
    # create a soup object
    soup = BeautifulSoup(html_string, "html.parser")
    
    '''
    Click the URL and investigate how you can pull movie_id, rank, title,... from the webpage.
    To investigate the html of a web page , For example:
    URL: https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc
    Right-click anywhere on the webpage, and at the very bottom of the menu that pops up, 
    you will see "Inspect", Click on it.
    '''
    '''
    Fetching a div that includes all the movies. This can be done by using find and find_all functions.
    for example, find_all('div') will give you all divs on the page. Actually, 
    this find or find_all function can have two parameters,
    in the code below 'div' is the tag name and 'ipc-page-grid__item ipc-page-grid__item--span-2' is an attribute 
    value of the tag. You can also do movie_list = soup.find('div', 'ipc-page-grid__item ipc-page-grid__item--span-2'). 
    Here you explicitly say: I want to find a div with 
    attribute class = 'ipc-page-grid__item ipc-page-grid__item--span-2'.
    
    Since on each imdb page, there's only one div with class = 'lister-list', we can use find rather than find_all. 
    Find_all will return a list of div tags, while find() will return only one div.
   '''     
    movie_list = soup.find('div', 'ipc-page-grid__item ipc-page-grid__item--span-2') 
    # this div contains all the listed movies in the requested html web page string.
    
    list_movies = [] # initialize the function return value, which is a list of movies. 
                     # This list will contains the scraped data transformed to a structured format.
    
    # Using count track the number of movies processed. now it's 0 - No movie has been processed yet.
    count = 0
    
    # each movie listed in a div with attribute value 'ipc-metadata-list-summary-item'.
    divs=  movie_list.find_all('li','ipc-metadata-list-summary-item') # To find all the listed movies in the page.
    for d in divs:
        dict_each_movie = {}  # initialize the movie dictionary to store the movie information.

        # Pulling the movie_id
        try:
            movie_id= d.find('a', 'ipc-title-link-wrapper').attrs['href']
            movie_id= movie_id[7:16]
            
        except:
            movie_id=""
        finally:
            dict_each_movie["movie_id"] = movie_id
            print(movie_id)
            
        # Pulling the rank
        try:
            rank = d.find('h3', 'ipc-title__text').text
            rank = rank.split('.')[0]  # Extract just the number before the period
        except:
            rank = ""
        finally:
            dict_each_movie["rank"] = rank
            print(f"Rank: {rank}")
        
        # Pulling the title
        try:
            title = d.find('h3', 'ipc-title__text').text
            title = title.split('. ', 1)[1]  # Get everything after "1. "
        except:
            title = ""
        finally:
            dict_each_movie["title"] = title
            print(f"Title: {title}")
        
        # Pulling the runtime
        try:
            metadata_items = d.find_all('span', 'dli-title-metadata-item')
            runtime = metadata_items[1].text if len(metadata_items) > 1 else ""
        except:
            runtime = ""
        finally:
            dict_each_movie["runtime"] = runtime
            print(f"Runtime: {runtime}")
        
        # Pulling the year
        try:
            metadata_items = d.find_all('span', 'dli-title-metadata-item')
            year = metadata_items[0].text if len(metadata_items) > 0 else ""
        except:
            year = ""
        finally:
            dict_each_movie["year"] = year
            print(f"Year: {year}")
        
        # Pulling the rating
        try:
            rating = d.find('span', 'ipc-rating-star--rating').text
        except:
            rating = ""
        finally:
            dict_each_movie["rating"] = rating
            print(f"Rating: {rating}")
        
        # Pulling the votes
        try:
            votes = d.find('span', 'ipc-rating-star--voteCount').text
            votes = votes.strip().replace('(', '').replace(')', '')
        except:
            votes = ""
        finally:
            dict_each_movie["votes"] = votes
            print(f"Votes: {votes}")        
        
        list_movies.append(dict_each_movie)  # To add the movie information to the movies list.

        count +=1
        print('===============================')
        print()
        if count == num_of_m:
            break # to exit from the loop.

    return list_movies

###  Call statement to scrap the TopVoted 500 movies
##### read_m_from_html_string(url,500)

In [3]:
url = "https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc"

Movies_list = read_m_from_html_string(url,500)  #to read the topVoted 500 movies
Movies_list

https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc
tt7286456
Rank: 1
Title: Joker
Runtime: 2h 2m
Year: 2019
Rating: 8.3
Votes: 1.7M
===============================

tt4154796
Rank: 2
Title: Avengers: Endgame
Runtime: 3h 1m
Year: 2019
Rating: 8.4
Votes: 1.4M
===============================

tt4154756
Rank: 3
Title: Avengers: Infinity War
Runtime: 2h 29m
Year: 2018
Rating: 8.4
Votes: 1.3M
===============================

tt6751668
Rank: 4
Title: Parasite
Runtime: 2h 12m
Year: 2019
Rating: 8.5
Votes: 1.1M
===============================

tt7131622
Rank: 5
Title: Once Upon a Time... in Hollywood
Runtime: 2h 41m
Year: 2019
Rating: 7.6
Votes: 936K
===============================

tt1825683
Rank: 6
Title: Black Panther
Runtime: 2h 14m
Year: 2018
Rating: 7.3
Votes: 893K
===============================

tt8946378
Rank: 7
Title: Knives Out
Runtime: 2h 10m
Year: 2019
Rating: 7.9
Votes: 837K
===============================

tt4633694
Rank: 8
Title: Spider-Man: Into the Spider-Verse
Runtime: 1h 57m
Year: 2018
Rating: 8.4
Votes: 758K
===============================

tt8579674
Rank: 9
Title: 1917
Runtime: 1h 59m
Year: 2019
Rating: 8.2
Votes: 749K
===============================

tt5463162
Rank: 10
Title: Deadpool 2
Runtime: 1h 59m
Year: 2018
Rating: 7.6
Votes: 729K
===============================

tt6966692
Rank: 11
Title: Green Book
Runtime: 2h 10m
Year: 2018
Rating: 8.2
Votes: 661K
===============================

tt6723592
Rank: 12
Title: Tenet
Runtime: 2h 30m
Year: 2020
Rating: 7.3
Votes: 648K
===============================

tt4154664
Rank: 13
Title: Captain Marvel
Runtime: 2h 3m
Year: 2019
Rating: 6.7
Votes: 646K
===============================

tt6644200
Rank: 14
Title: A Quiet Place
Runtime: 1h 30m
Year: 2018
Rating: 7.5
Votes: 644K
===============================

tt1727824
Rank: 15
Title: Bohemian Rhapsody
Runtime: 2h 14m
Year: 2018
Rating: 7.9
Votes: 633K
===============================

tt6320628
Rank: 16
Title: Spider-Man: Far from Home
Runtime: 2h 9m
Year: 2019
Rating: 7.3
Votes: 618K
===============================

tt1270797
Rank: 17
Title: Venom
Runtime: 1h 52m
Year: 2018
Rating: 6.6
Votes: 593K
===============================

tt1950186
Rank: 18
Title: Ford v Ferrari
Runtime: 2h 32m
Year: 2019
Rating: 8.1
Votes: 548K
===============================

tt1477834
Rank: 19
Title: Aquaman
Runtime: 2h 23m
Year: 2018
Rating: 6.8
Votes: 546K
===============================

tt2527338
Rank: 20
Title: Star Wars: Episode IX - The Rise of Skywalker
Runtime: 2h 21m
Year: 2019
Rating: 6.4
Votes: 530K
===============================

tt1677720
Rank: 21
Title: Ready Player One
Runtime: 2h 20m
Year: 2018
Rating: 7.4
Votes: 530K
===============================

tt5095030
Rank: 22
Title: Ant-Man and the Wasp
Runtime: 1h 58m
Year: 2018
Rating: 7.0
Votes: 484K
===============================

tt2584384
Rank: 23
Title: Jojo Rabbit
Runtime: 1h 48m
Year: 2019
Rating: 7.9
Votes: 478K
===============================

tt6146586
Rank: 24
Title: John Wick: Chapter 3 - Parabellum
Runtime: 2h 10m
Year: 2019
Rating: 7.4
Votes: 468K
===============================

tt8772262
Rank: 25
Title: Midsommar
Runtime: 2h 28m
Year: 2019
Rating: 7.1
Votes: 468K
===============================

tt1302006
Rank: 26
Title: The Irishman
Runtime: 3h 29m
Year: 2019
Rating: 7.8
Votes: 462K
===============================

tt8367814
Rank: 27
Title: The Gentlemen
Runtime: 1h 53m
Year: 2019
Rating: 7.8
Votes: 445K
===============================

tt1517451
Rank: 28
Title: A Star Is Born
Runtime: 2h 16m
Year: 2018
Rating: 7.6
Votes: 442K
===============================

tt7784604
Rank: 29
Title: Hereditary
Runtime: 2h 7m
Year: 2018
Rating: 7.3
Votes: 440K
===============================

tt2948372
Rank: 30
Title: Soul
Runtime: 1h 40m
Year: 2020
Rating: 8.0
Votes: 419K
===============================

tt2737304
Rank: 31
Title: Bird Box
Runtime: 2h 4m
Year: 2018
Rating: 6.6
Votes: 414K
===============================

tt4912910
Rank: 32
Title: Mission: Impossible - Fallout
Runtime: 2h 27m
Year: 2018
Rating: 7.7
Votes: 412K
===============================

tt0448115
Rank: 33
Title: Shazam!
Runtime: 2h 12m
Year: 2019
Rating: 7.0
Votes: 408K
===============================

tt3778644
Rank: 34
Title: Solo: A Star Wars Story
Runtime: 2h 15m
Year: 2018
Rating: 6.9
Votes: 402K
===============================

tt2798920
Rank: 35
Title: Annihilation
Runtime: 1h 55m
Year: 2018
Rating: 6.8
Votes: 387K
===============================

tt6857112
Rank: 36
Title: Us
Runtime: 1h 56m
Year: 2019
Rating: 6.8
Votes: 381K
===============================

tt4881806
Rank: 37
Title: Jurassic World: Fallen Kingdom
Runtime: 2h 8m
Year: 2018
Rating: 6.1
Votes: 373K
===============================

tt7653254
Rank: 38
Title: Marriage Story
Runtime: 2h 17m
Year: 2019
Rating: 7.9
Votes: 366K
===============================

tt3606756
Rank: 39
Title: Incredibles 2
Runtime: 1h 58m
Year: 2018
Rating: 7.5
Votes: 361K
===============================

tt5727208
Rank: 40
Title: Uncut Gems
Runtime: 2h 15m
Year: 2019
Rating: 7.4
Votes: 343K
===============================

tt7349950
Rank: 41
Title: It: Chapter Two
Runtime: 2h 49m
Year: 2019
Rating: 6.5
Votes: 338K
===============================

tt9243946
Rank: 42
Title: El Camino
Runtime: 2h 2m
Year: 2019
Rating: 7.3
Votes: 328K
===============================

tt4123430
Rank: 43
Title: Fantastic Beasts: The Crimes of Grindelwald
Runtime: 2h 14m
Year: 2018
Rating: 6.5
Votes: 326K
===============================

tt0437086
Rank: 44
Title: Alita: Battle Angel
Runtime: 2h 2m
Year: 2019
Rating: 7.3
Votes: 318K
===============================

tt8228288
Rank: 45
Title: The Platform
Runtime: 1h 34m
Year: 2019
Rating: 7.0
Votes: 316K
===============================

tt8332922
Rank: 46
Title: A Quiet Place Part II
Runtime: 1h 37m
Year: 2020
Rating: 7.2
Votes: 314K
===============================

tt7975244
Rank: 47
Title: Jumanji: The Next Level
Runtime: 2h 3m
Year: 2019
Rating: 6.6
Votes: 311K
===============================

tt6139732
Rank: 48
Title: Aladdin
Runtime: 2h 8m
Year: 2019
Rating: 6.9
Votes: 309K
===============================

tt7349662
Rank: 49
Title: BlacKkKlansman
Runtime: 2h 15m
Year: 2018
Rating: 7.5
Votes: 308K
===============================

tt7126948
Rank: 50
Title: Wonder Woman 1984
Runtime: 2h 31m
Year: 2020
Rating: 5.3
Votes: 307K
===============================

tt1979376
Rank: 51
Title: Toy Story 4
Runtime: 1h 40m
Year: 2019
Rating: 7.6
Votes: 305K
===============================

tt6823368
Rank: 52
Title: Glass
Runtime: 2h 9m
Year: 2019
Rating: 6.6
Votes: 299K
===============================

tt7984734
Rank: 53
Title: The Lighthouse
Runtime: 1h 49m
Year: 2019
Rating: 7.4
Votes: 293K
===============================

tt6105098
Rank: 54
Title: The Lion King
Runtime: 1h 58m
Year: 2019
Rating: 6.8
Votes: 287K
===============================

tt8936646
Rank: 55
Title: Extraction
Runtime: 1h 56m
Year: 2020
Rating: 6.8
Votes: 284K
===============================

tt7713068
Rank: 56
Title: Birds of Prey and the Fantabulous Emancipation of One Harley Quinn
Runtime: 1h 49m
Year: 2020
Rating: 6.1
Votes: 279K
===============================

tt1051906
Rank: 57
Title: The Invisible Man
Runtime: 2h 4m
Year: 2020
Rating: 7.1
Votes: 278K
===============================

tt3281548
Rank: 58
Title: Little Women
Runtime: 2h 15m
Year: 2019
Rating: 7.8
Votes: 276K
===============================

tt2935510
Rank: 59
Title: Ad Astra
Runtime: 2h 3m
Year: 2019
Rating: 6.5
Votes: 275K
===============================

tt2704998
Rank: 60
Title: Game Night
Runtime: 1h 40m
Year: 2018
Rating: 6.9
Votes: 271K
===============================

tt5164214
Rank: 61
Title: Ocean's Eight
Runtime: 1h 50m
Year: 2018
Rating: 6.3
Votes: 257K
===============================

tt5083738
Rank: 62
Title: The Favourite
Runtime: 1h 59m
Year: 2018
Rating: 7.5
Votes: 253K
===============================

tt6806448
Rank: 63
Title: Fast & Furious Presents: Hobbs & Shaw
Runtime: 2h 17m
Year: 2019
Rating: 6.4
Votes: 252K
===============================

tt7846844
Rank: 64
Title: Enola Holmes
Runtime: 2h 3m
Year: 2020
Rating: 6.6
Votes: 239K
===============================

tt5606664
Rank: 65
Title: Doctor Sleep
Runtime: 2h 32m
Year: 2019
Rating: 7.3
Votes: 238K
===============================

tt1365519
Rank: 66
Title: Tomb Raider
Runtime: 1h 59m
Year: 2018
Rating: 6.3
Votes: 238K
===============================

tt9620292
Rank: 67
Title: Promising Young Woman
Runtime: 1h 53m
Year: 2020
Rating: 7.5
Votes: 231K
===============================

tt6499752
Rank: 68
Title: Upgrade
Runtime: 1h 40m
Year: 2018
Rating: 7.5
Votes: 229K
===============================

tt7798634
Rank: 69
Title: Ready or Not
Runtime: 1h 35m
Year: 2019
Rating: 6.8
Votes: 225K
===============================

tt3741700
Rank: 70
Title: Godzilla: King of the Monsters
Runtime: 2h 12m
Year: 2019
Rating: 6.0
Votes: 224K
===============================

tt4779682
Rank: 71
Title: The Meg
Runtime: 1h 53m
Year: 2018
Rating: 5.7
Votes: 224K
===============================

tt6565702
Rank: 72
Title: X-Men: Dark Phoenix
Runtime: 1h 53m
Year: 2019
Rating: 5.7
Votes: 223K
===============================

tt3766354
Rank: 73
Title: The Equalizer 2
Runtime: 2h 1m
Year: 2018
Rating: 6.7
Votes: 223K
===============================

tt4729430
Rank: 74
Title: Klaus
Runtime: 1h 36m
Year: 2019
Rating: 8.2
Votes: 222K
===============================

tt1027238
Rank: 75
Title: The Father
Runtime: 1h 37m
Year: 2020
Rating: 8.2
Votes: 221K
===============================

tt1560220
Rank: 76
Title: Zombieland: Double Tap
Runtime: 1h 39m
Year: 2019
Rating: 6.7
Votes: 220K
===============================

tt1028856
Rank: 77
Title: Another Round
Runtime: 1h 57m
Year: 2020
Rating: 7.7
Votes: 220K
===============================

tt2873282
Rank: 78
Title: Red Sparrow
Runtime: 2h 20m
Year: 2018
Rating: 6.6
Votes: 215K
===============================

tt1213641
Rank: 79
Title: First Man
Runtime: 2h 21m
Year: 2018
Rating: 7.3
Votes: 213K
===============================

tt4520988
Rank: 80
Title: Frozen II
Runtime: 1h 43m
Year: 2019
Rating: 6.8
Votes: 213K
===============================

tt6450804
Rank: 81
Title: Terminator: Dark Fate
Runtime: 2h 8m
Year: 2019
Rating: 6.2
Votes: 208K
===============================

tt8106534
Rank: 82
Title: 6 Underground
Runtime: 2h 8m
Year: 2019
Rating: 6.1
Votes: 208K
===============================

tt9484998
Rank: 83
Title: Palm Springs
Runtime: 1h 30m
Year: 2020
Rating: 7.4
Votes: 207K
===============================

tt7556122
Rank: 84
Title: The Old Guard
Runtime: 2h 5m
Year: 2020
Rating: 6.7
Votes: 207K
===============================

tt2066051
Rank: 85
Title: Rocketman
Runtime: 2h 1m
Year: 2019
Rating: 7.3
Votes: 206K
===============================

tt5104604
Rank: 86
Title: Isle of Dogs
Runtime: 1h 41m
Year: 2018
Rating: 7.8
Votes: 206K
===============================

tt3104988
Rank: 87
Title: Crazy Rich Asians
Runtime: 2h
Year: 2018
Rating: 6.9
Votes: 205K
===============================

tt4701182
Rank: 88
Title: Bumblebee
Runtime: 1h 54m
Year: 2018
Rating: 6.7
Votes: 204K
===============================

tt1070874
Rank: 89
Title: The Trial of the Chicago 7
Runtime: 2h 9m
Year: 2020
Rating: 7.7
Votes: 203K
===============================

tt5848272
Rank: 90
Title: Ralph Breaks the Internet
Runtime: 1h 52m
Year: 2018
Rating: 7.0
Votes: 200K
===============================

tt2231461
Rank: 91
Title: Rampage
Runtime: 1h 47m
Year: 2018
Rating: 6.1
Votes: 198K
===============================

tt9770150
Rank: 92
Title: Nomadland
Runtime: 1h 47m
Year: 2020
Rating: 7.3
Votes: 197K
===============================

tt1502397
Rank: 93
Title: Bad Boys for Life
Runtime: 2h 4m
Year: 2020
Rating: 6.5
Votes: 194K
===============================

tt5884052
Rank: 94
Title: Pokémon: Detective Pikachu
Runtime: 1h 44m
Year: 2019
Rating: 6.5
Votes: 194K
===============================

tt5814060
Rank: 95
Title: The Nun
Runtime: 1h 36m
Year: 2018
Rating: 5.4
Votes: 191K
===============================

tt7668870
Rank: 96
Title: Searching
Runtime: 1h 42m
Year: 2018
Rating: 7.6
Votes: 190K
===============================

tt7040874
Rank: 97
Title: A Simple Favor
Runtime: 1h 57m
Year: 2018
Rating: 6.7
Votes: 188K
===============================

tt3794354
Rank: 98
Title: Sonic the Hedgehog
Runtime: 1h 39m
Year: 2020
Rating: 6.5
Votes: 187K
===============================

tt1618434
Rank: 99
Title: Murder Mystery
Runtime: 1h 37m
Year: 2019
Rating: 6.1
Votes: 185K
===============================

tt5052474
Rank: 100
Title: Sicario: Day of the Soldado
Runtime: 2h 2m
Year: 2018
Rating: 7.1
Votes: 185K
===============================

tt4500922
Rank: 101
Title: Maze Runner: The Death Cure
Runtime: 2h 23m
Year: 2018
Rating: 6.3
Votes: 184K
===============================

tt1502407
Rank: 102
Title: Halloween
Runtime: 1h 46m
Year: 2018
Rating: 6.5
Votes: 184K
===============================

tt7146812
Rank: 103
Title: Onward
Runtime: 1h 42m
Year: 2020
Rating: 7.4
Votes: 183K
===============================

tt8079248
Rank: 104
Title: Yesterday
Runtime: 1h 56m
Year: 2019
Rating: 6.8
Votes: 181K
===============================

tt6412452
Rank: 105
Title: The Ballad of Buster Scruggs
Runtime: 2h 13m
Year: 2018
Rating: 7.2
Votes: 180K
===============================

tt6155172
Rank: 106
Title: Roma
Runtime: 2h 15m
Year: 2018
Rating: 7.6
Votes: 176K
===============================

tt6628394
Rank: 107
Title: Bad Times at the El Royale
Runtime: 2h 21m
Year: 2018
Rating: 7.1
Votes: 176K
===============================

tt2386490
Rank: 108
Title: How to Train Your Dragon: The Hidden World
Runtime: 1h 44m
Year: 2019
Rating: 7.4
Votes: 173K
===============================

tt6266538
Rank: 109
Title: Vice
Runtime: 2h 12m
Year: 2018
Rating: 7.2
Votes: 172K
===============================

tt7984766
Rank: 110
Title: The King
Runtime: 2h 20m
Year: 2019
Rating: 7.3
Votes: 171K
===============================

tt6343314
Rank: 111
Title: Creed II
Runtime: 2h 10m
Year: 2018
Rating: 7.1
Votes: 167K
===============================

tt4566758
Rank: 112
Title: Mulan
Runtime: 1h 55m
Year: 2020
Rating: 5.8
Votes: 166K
===============================

tt7959026
Rank: 113
Title: The Mule
Runtime: 1h 56m
Year: 2018
Rating: 7.0
Votes: 166K
===============================

tt7395114
Rank: 114
Title: The Devil All the Time
Runtime: 2h 18m
Year: 2020
Rating: 7.1
Votes: 165K
===============================

tt5363618
Rank: 115
Title: Sound of Metal
Runtime: 2h
Year: 2019
Rating: 7.7
Votes: 164K
===============================

tt1314396
Rank: 116
Title: Borat Subsequent Moviefilm
Runtime: 1h 35m
Year: 2020
Rating: 6.6
Votes: 162K
===============================

tt2854926
Rank: 117
Title: Tag
Runtime: 1h 40m
Year: 2018
Rating: 6.5
Votes: 159K
===============================

tt3829266
Rank: 118
Title: The Predator
Runtime: 1h 47m
Year: 2018
Rating: 5.3
Votes: 158K
===============================

tt1488606
Rank: 119
Title: Triple Frontier
Runtime: 2h 5m
Year: 2019
Rating: 6.5
Votes: 158K
===============================

tt2283336
Rank: 120
Title: Men in Black: International
Runtime: 1h 54m
Year: 2019
Rating: 5.6
Votes: 158K
===============================

tt2222042
Rank: 121
Title: Love and Monsters
Runtime: 1h 49m
Year: 2020
Rating: 6.9
Votes: 156K
===============================

tt9893250
Rank: 122
Title: I Care a Lot
Runtime: 1h 58m
Year: 2020
Rating: 6.4
Votes: 156K
===============================

tt5886046
Rank: 123
Title: Escape Room
Runtime: 1h 39m
Year: 2019
Rating: 6.4
Votes: 156K
===============================

tt7737786
Rank: 124
Title: Greenland
Runtime: 1h 59m
Year: 2020
Rating: 6.4
Votes: 151K
===============================

tt1571234
Rank: 125
Title: Mortal Engines
Runtime: 2h 8m
Year: 2018
Rating: 6.1
Votes: 151K
===============================

tt1259528
Rank: 126
Title: Den of Thieves
Runtime: 2h 20m
Year: 2018
Rating: 7.0
Votes: 150K
===============================

tt8244784
Rank: 127
Title: The Hunt
Runtime: 1h 30m
Year: 2020
Rating: 6.6
Votes: 149K
===============================

tt8404614
Rank: 128
Title: The Two Popes
Runtime: 2h 5m
Year: 2019
Rating: 7.6
Votes: 144K
===============================

tt5758778
Rank: 129
Title: Skyscraper
Runtime: 1h 42m
Year: 2018
Rating: 5.8
Votes: 143K
===============================

tt9495224
Rank: 130
Title: Black Mirror: Bandersnatch
Runtime: 1h 30m
Year: 2018
Rating: 7.1
Votes: 142K
===============================

tt1489887
Rank: 131
Title: Booksmart
Runtime: 1h 42m
Year: 2019
Rating: 7.1
Votes: 138K
===============================

tt8110330
Rank: 132
Title: Dil Bechara
Runtime: 1h 41m
Year: 2020
Rating: 8.3
Votes: 137K
===============================

tt3846674
Rank: 133
Title: To All the Boys I've Loved Before
Runtime: 1h 39m
Year: 2018
Rating: 7.0
Votes: 136K
===============================

tt2557478
Rank: 134
Title: Pacific Rim: Uprising
Runtime: 1h 51m
Year: 2018
Rating: 5.6
Votes: 135K
===============================

tt8503618
Rank: 135
Title: Hamilton
Runtime: 2h 40m
Year: 2020
Rating: 8.3
Votes: 134K
===============================

tt6394270
Rank: 136
Title: Bombshell
Runtime: 1h 49m
Year: 2019
Rating: 6.8
Votes: 134K
===============================

tt7401588
Rank: 137
Title: Instant Family
Runtime: 1h 58m
Year: 2018
Rating: 7.3
Votes: 133K
===============================

tt5164432
Rank: 138
Title: Love, Simon
Runtime: 1h 50m
Year: 2018
Rating: 7.5
Votes: 132K
===============================

tt1590193
Rank: 139
Title: The Commuter
Runtime: 1h 44m
Year: 2018
Rating: 6.3
Votes: 132K
===============================

tt1018951
Rank: 140
Title: Soorarai Pottru
Runtime: 2h 33m
Year: 2020
Rating: 8.6
Votes: 130K
===============================

tt4777008
Rank: 141
Title: Maleficent: Mistress of Evil
Runtime: 1h 59m
Year: 2019
Rating: 6.6
Votes: 129K
===============================

tt1025100
Rank: 142
Title: Gemini Man
Runtime: 1h 57m
Year: 2019
Rating: 5.7
Votes: 129K
===============================

tt6048922
Rank: 143
Title: Greyhound
Runtime: 1h 31m
Year: 2020
Rating: 7.0
Votes: 128K
===============================

tt2139881
Rank: 144
Title: Long Shot
Runtime: 2h 5m
Year: 2019
Rating: 6.8
Votes: 127K
===============================

tt8613070
Rank: 145
Title: Portrait of a Lady on Fire
Runtime: 2h 2m
Year: 2019
Rating: 8.0
Votes: 123K
===============================

tt1226837
Rank: 146
Title: Beautiful Boy
Runtime: 2h
Year: 2018
Rating: 7.4
Votes: 121K
===============================

tt8267604
Rank: 147
Title: Capernaum
Runtime: 2h 6m
Year: 2018
Rating: 8.4
Votes: 120K
===============================

tt6189022
Rank: 148
Title: Angel Has Fallen
Runtime: 2h 1m
Year: 2019
Rating: 6.4
Votes: 120K
===============================

tt2548396
Rank: 149
Title: The Cloverfield Paradox
Runtime: 1h 42m
Year: 2018
Rating: 5.5
Votes: 119K
===============================

tt9071322
Rank: 150
Title: Dark Waters
Runtime: 2h 6m
Year: 2019
Rating: 7.6
Votes: 119K
===============================

tt6911608
Rank: 151
Title: Mamma Mia! Here We Go Again
Runtime: 1h 54m
Year: 2018
Rating: 6.6
Votes: 118K
===============================

tt1206885
Rank: 152
Title: Rambo: Last Blood
Runtime: 1h 29m
Year: 2019
Rating: 6.1
Votes: 117K
===============================

tt7752126
Rank: 153
Title: Brightburn
Runtime: 1h 30m
Year: 2019
Rating: 6.1
Votes: 117K
===============================

tt4364194
Rank: 154
Title: The Peanut Butter Falcon
Runtime: 1h 37m
Year: 2019
Rating: 7.6
Votes: 117K
===============================

tt4530422
Rank: 155
Title: Overlord
Runtime: 1h 50m
Year: 2018
Rating: 6.6
Votes: 114K
===============================

tt8108198
Rank: 156
Title: Andhadhun
Runtime: 2h 19m
Year: 2018
Rating: 8.2
Votes: 112K
===============================

tt5503686
Rank: 157
Title: Hustlers
Runtime: 1h 50m
Year: 2019
Rating: 6.3
Votes: 112K
===============================

tt1860242
Rank: 158
Title: The Highwaymen
Runtime: 2h 12m
Year: 2019
Rating: 6.9

[{'movie_id': 'tt7286456',
  'rank': '1',
  'title': 'Joker',
  'runtime': '2h 2m',
  'year': '2019',
  'rating': '8.3',
  'votes': '1.7M'},
 {'movie_id': 'tt4154796',
  'rank': '2',
  'title': 'Avengers: Endgame',
  'runtime': '3h 1m',
  'year': '2019',
  'rating': '8.4',
  'votes': '1.4M'},
 {'movie_id': 'tt4154756',
  'rank': '3',
  'title': 'Avengers: Infinity War',
  'runtime': '2h 29m',
  'year': '2018',
  'rating': '8.4',
  'votes': '1.3M'},
 {'movie_id': 'tt6751668',
  'rank': '4',
  'title': 'Parasite',
  'runtime': '2h 12m',
  'year': '2019',
  'rating': '8.5',
  'votes': '1.1M'},
 {'movie_id': 'tt7131622',
  'rank': '5',
  'title': 'Once Upon a Time... in Hollywood',
  'runtime': '2h 41m',
  'year': '2019',
  'rating': '7.6',
  'votes': '936K'},
 {'movie_id': 'tt1825683',
  'rank': '6',
  'title': 'Black Panther',
  'runtime': '2h 14m',
  'year': '2018',
  'rating': '7.3',
  'votes': '893K'},
 {'movie_id': 'tt8946378',
  'rank': '7',
  'title': 'Knives Out',
  'runtime': '2h 10m',
  'year': '2019',
  'rating': '7.9',
  'votes': '837K'},
 {'movie_id': 'tt4633694',
  'rank': '8',
  'title': 'Spider-Man: Into the Spider-Verse',
  'runtime': '1h 57m',
  'year': '2018',
  'rating': '8.4',
  'votes': '758K'},
 {'movie_id': 'tt8579674',
  'rank': '9',
  'title': '1917',
  'runtime': '1h 59m',
  'year': '2019',
  'rating': '8.2',
  'votes': '749K'},
 {'movie_id': 'tt5463162',
  'rank': '10',
  'title': 'Deadpool 2',
  'runtime': '1h 59m',
  'year': '2018',
  'rating': '7.6',
  'votes': '729K'},
 {'movie_id': 'tt6966692',
  'rank': '11',
  'title': 'Green Book',
  'runtime': '2h 10m',
  'year': '2018',
  'rating': '8.2',
  'votes': '661K'},
 {'movie_id': 'tt6723592',
  'rank': '12',
  'title': 'Tenet',
  'runtime': '2h 30m',
  'year': '2020',
  'rating': '7.3',
  'votes': '648K'},
 {'movie_id': 'tt4154664',
  'rank': '13',
  'title': 'Captain Marvel',
  'runtime': '2h 3m',
  'year': '2019',
  'rating': '6.7',
  'votes': '646K'},
 {'movie_id': 'tt6644200',
  'rank': '14',
  'title': 'A Quiet Place',
  'runtime': '1h 30m',
  'year': '2018',
  'rating': '7.5',
  'votes': '644K'},
 {'movie_id': 'tt1727824',
  'rank': '15',
  'title': 'Bohemian Rhapsody',
  'runtime': '2h 14m',
  'year': '2018',
  'rating': '7.9',
  'votes': '633K'},
 {'movie_id': 'tt6320628',
  'rank': '16',
  'title': 'Spider-Man: Far from Home',
  'runtime': '2h 9m',
  'year': '2019',
  'rating': '7.3',
  'votes': '618K'},
 {'movie_id': 'tt1270797',
  'rank': '17',
  'title': 'Venom',
  'runtime': '1h 52m',
  'year': '2018',
  'rating': '6.6',
  'votes': '593K'},
 {'movie_id': 'tt1950186',
  'rank': '18',
  'title': 'Ford v Ferrari',
  'runtime': '2h 32m',
  'year': '2019',
  'rating': '8.1',
  'votes': '548K'},
 {'movie_id': 'tt1477834',
  'rank': '19',
  'title': 'Aquaman',
  'runtime': '2h 23m',
  'year': '2018',
  'rating': '6.8',
  'votes': '546K'},
 {'movie_id': 'tt2527338',
  'rank': '20',
  'title': 'Star Wars: Episode IX - The Rise of Skywalker',
  'runtime': '2h 21m',
  'year': '2019',
  'rating': '6.4',
  'votes': '530K'},
 {'movie_id': 'tt1677720',
  'rank': '21',
  'title': 'Ready Player One',
  'runtime': '2h 20m',
  'year': '2018',
  'rating': '7.4',
  'votes': '530K'},
 {'movie_id': 'tt5095030',
  'rank': '22',
  'title': 'Ant-Man and the Wasp',
  'runtime': '1h 58m',
  'year': '2018',
  'rating': '7.0',
  'votes': '484K'},
 {'movie_id': 'tt2584384',
  'rank': '23',
  'title': 'Jojo Rabbit',
  'runtime': '1h 48m',
  'year': '2019',
  'rating': '7.9',
  'votes': '478K'},
 {'movie_id': 'tt6146586',
  'rank': '24',
  'title': 'John Wick: Chapter 3 - Parabellum',
  'runtime': '2h 10m',
  'year': '2019',
  'rating': '7.4',
  'votes': '468K'},
 {'movie_id': 'tt8772262',
  'rank': '25',
  'title': 'Midsommar',
  'runtime': '2h 28m',
  'year': '2019',
  'rating': '7.1',
  'votes': '468K'},
 {'movie_id': 'tt1302006',
  'rank': '26',
  'title': 'The Irishman',
  'runtime': '3h 29m',
  'year': '2019',
  'rating': '7.8',
  'votes': '462K'},
 {'movie_id': 'tt8367814',
  'rank': '27',
  'title': 'The Gentlemen',
  'runtime': '1h 53m',
  'year': '2019',
  'rating': '7.8',
  'votes': '445K'},
 {'movie_id': 'tt1517451',
  'rank': '28',
  'title': 'A Star Is Born',
  'runtime': '2h 16m',
  'year': '2018',
  'rating': '7.6',
  'votes': '442K'},
 {'movie_id': 'tt7784604',
  'rank': '29',
  'title': 'Hereditary',
  'runtime': '2h 7m',
  'year': '2018',
  'rating': '7.3',
  'votes': '440K'},
 {'movie_id': 'tt2948372',
  'rank': '30',
  'title': 'Soul',
  'runtime': '1h 40m',
  'year': '2020',
  'rating': '8.0',
  'votes': '419K'},
 {'movie_id': 'tt2737304',
  'rank': '31',
  'title': 'Bird Box',
  'runtime': '2h 4m',
  'year': '2018',
  'rating': '6.6',
  'votes': '414K'},
 {'movie_id': 'tt4912910',
  'rank': '32',
  'title': 'Mission: Impossible - Fallout',
  'runtime': '2h 27m',
  'year': '2018',
  'rating': '7.7',
  'votes': '412K'},
 {'movie_id': 'tt0448115',
  'rank': '33',
  'title': 'Shazam!',
  'runtime': '2h 12m',
  'year': '2019',
  'rating': '7.0',
  'votes': '408K'},
 {'movie_id': 'tt3778644',
  'rank': '34',
  'title': 'Solo: A Star Wars Story',
  'runtime': '2h 15m',
  'year': '2018',
  'rating': '6.9',
  'votes': '402K'},
 {'movie_id': 'tt2798920',
  'rank': '35',
  'title': 'Annihilation',
  'runtime': '1h 55m',
  'year': '2018',
  'rating': '6.8',
  'votes': '387K'},
 {'movie_id': 'tt6857112',
  'rank': '36',
  'title': 'Us',
  'runtime': '1h 56m',
  'year': '2019',
  'rating': '6.8',
  'votes': '381K'},
 {'movie_id': 'tt4881806',
  'rank': '37',
  'title': 'Jurassic World: Fallen Kingdom',
  'runtime': '2h 8m',
  'year': '2018',
  'rating': '6.1',
  'votes': '373K'},
 {'movie_id': 'tt7653254',
  'rank': '38',
  'title': 'Marriage Story',
  'runtime': '2h 17m',
  'year': '2019',
  'rating': '7.9',
  'votes': '366K'},
 {'movie_id': 'tt3606756',
  'rank': '39',
  'title': 'Incredibles 2',
  'runtime': '1h 58m',
  'year': '2018',
  'rating': '7.5',
  'votes': '361K'},
 {'movie_id': 'tt5727208',
  'rank': '40',
  'title': 'Uncut Gems',
  'runtime': '2h 15m',
  'year': '2019',
  'rating': '7.4',
  'votes': '343K'},
 {'movie_id': 'tt7349950',
  'rank': '41',
  'title': 'It: Chapter Two',
  'runtime': '2h 49m',
  'year': '2019',
  'rating': '6.5',
  'votes': '338K'},
 {'movie_id': 'tt9243946',
  'rank': '42',
  'title': 'El Camino',
  'runtime': '2h 2m',
  'year': '2019',
  'rating': '7.3',
  'votes': '328K'},
 {'movie_id': 'tt4123430',
  'rank': '43',
  'title': 'Fantastic Beasts: The Crimes of Grindelwald',
  'runtime': '2h 14m',
  'year': '2018',
  'rating': '6.5',
  'votes': '326K'},
 {'movie_id': 'tt0437086',
  'rank': '44',
  'title': 'Alita: Battle Angel',
  'runtime': '2h 2m',
  'year': '2019',
  'rating': '7.3',
  'votes': '318K'},
 {'movie_id': 'tt8228288',
  'rank': '45',
  'title': 'The Platform',
  'runtime': '1h 34m',
  'year': '2019',
  'rating': '7.0',
  'votes': '316K'},
 {'movie_id': 'tt8332922',
  'rank': '46',
  'title': 'A Quiet Place Part II',
  'runtime': '1h 37m',
  'year': '2020',
  'rating': '7.2',
  'votes': '314K'},
 {'movie_id': 'tt7975244',
  'rank': '47',
  'title': 'Jumanji: The Next Level',
  'runtime': '2h 3m',
  'year': '2019',
  'rating': '6.6',
  'votes': '311K'},
 {'movie_id': 'tt6139732',
  'rank': '48',
  'title': 'Aladdin',
  'runtime': '2h 8m',
  'year': '2019',
  'rating': '6.9',
  'votes': '309K'},
 {'movie_id': 'tt7349662',
  'rank': '49',
  'title': 'BlacKkKlansman',
  'runtime': '2h 15m',
  'year': '2018',
  'rating': '7.5',
  'votes': '308K'},
 {'movie_id': 'tt7126948',
  'rank': '50',
  'title': 'Wonder Woman 1984',
  'runtime': '2h 31m',
  'year': '2020',
  'rating': '5.3',
  'votes': '307K'},
 {'movie_id': 'tt1979376',
  'rank': '51',
  'title': 'Toy Story 4',
  'runtime': '1h 40m',
  'year': '2019',
  'rating': '7.6',
  'votes': '305K'},
 {'movie_id': 'tt6823368',
  'rank': '52',
  'title': 'Glass',
  'runtime': '2h 9m',
  'year': '2019',
  'rating': '6.6',
  'votes': '299K'},
 {'movie_id': 'tt7984734',
  'rank': '53',
  'title': 'The Lighthouse',
  'runtime': '1h 49m',
  'year': '2019',
  'rating': '7.4',
  'votes': '293K'},
 {'movie_id': 'tt6105098',
  'rank': '54',
  'title': 'The Lion King',
  'runtime': '1h 58m',
  'year': '2019',
  'rating': '6.8',
  'votes': '287K'},
 {'movie_id': 'tt8936646',
  'rank': '55',
  'title': 'Extraction',
  'runtime': '1h 56m',
  'year': '2020',
  'rating': '6.8',
  'votes': '284K'},
 {'movie_id': 'tt7713068',
  'rank': '56',
  'title': 'Birds of Prey and the Fantabulous Emancipation of One Harley Quinn',
  'runtime': '1h 49m',
  'year': '2020',
  'rating': '6.1',
  'votes': '279K'},
 {'movie_id': 'tt1051906',
  'rank': '57',
  'title': 'The Invisible Man',
  'runtime': '2h 4m',
  'year': '2020',
  'rating': '7.1',
  'votes': '278K'},
 {'movie_id': 'tt3281548',
  'rank': '58',
  'title': 'Little Women',
  'runtime': '2h 15m',
  'year': '2019',
  'rating': '7.8',
  'votes': '276K'},
 {'movie_id': 'tt2935510',
  'rank': '59',
  'title': 'Ad Astra',
  'runtime': '2h 3m',
  'year': '2019',
  'rating': '6.5',
  'votes': '275K'},
 {'movie_id': 'tt2704998',
  'rank': '60',
  'title': 'Game Night',
  'runtime': '1h 40m',
  'year': '2018',
  'rating': '6.9',
  'votes': '271K'},
 {'movie_id': 'tt5164214',
  'rank': '61',
  'title': "Ocean's Eight",
  'runtime': '1h 50m',
  'year': '2018',
  'rating': '6.3',
  'votes': '257K'},
 {'movie_id': 'tt5083738',
  'rank': '62',
  'title': 'The Favourite',
  'runtime': '1h 59m',
  'year': '2018',
  'rating': '7.5',
  'votes': '253K'},
 {'movie_id': 'tt6806448',
  'rank': '63',
  'title': 'Fast & Furious Presents: Hobbs & Shaw',
  'runtime': '2h 17m',
  'year': '2019',
  'rating': '6.4',
  'votes': '252K'},
 {'movie_id': 'tt7846844',
  'rank': '64',
  'title': 'Enola Holmes',
  'runtime': '2h 3m',
  'year': '2020',
  'rating': '6.6',
  'votes': '239K'},
 {'movie_id': 'tt5606664',
  'rank': '65',
  'title': 'Doctor Sleep',
  'runtime': '2h 32m',
  'year': '2019',
  'rating': '7.3',
  'votes': '238K'},
 {'movie_id': 'tt1365519',
  'rank': '66',
  'title': 'Tomb Raider',
  'runtime': '1h 59m',
  'year': '2018',
  'rating': '6.3',
  'votes': '238K'},
 {'movie_id': 'tt9620292',
  'rank': '67',
  'title': 'Promising Young Woman',
  'runtime': '1h 53m',
  'year': '2020',
  'rating': '7.5',
  'votes': '231K'},
 {'movie_id': 'tt6499752',
  'rank': '68',
  'title': 'Upgrade',
  'runtime': '1h 40m',
  'year': '2018',
  'rating': '7.5',
  'votes': '229K'},
 {'movie_id': 'tt7798634',
  'rank': '69',
  'title': 'Ready or Not',
  'runtime': '1h 35m',
  'year': '2019',
  'rating': '6.8',
  'votes': '225K'},
 {'movie_id': 'tt3741700',
  'rank': '70',
  'title': 'Godzilla: King of the Monsters',
  'runtime': '2h 12m',
  'year': '2019',
  'rating': '6.0',
  'votes': '224K'},
 {'movie_id': 'tt4779682',
  'rank': '71',
  'title': 'The Meg',
  'runtime': '1h 53m',
  'year': '2018',
  'rating': '5.7',
  'votes': '224K'},
 {'movie_id': 'tt6565702',
  'rank': '72',
  'title': 'X-Men: Dark Phoenix',
  'runtime': '1h 53m',
  'year': '2019',
  'rating': '5.7',
  'votes': '223K'},
 {'movie_id': 'tt3766354',
  'rank': '73',
  'title': 'The Equalizer 2',
  'runtime': '2h 1m',
  'year': '2018',
  'rating': '6.7',
  'votes': '223K'},
 {'movie_id': 'tt4729430',
  'rank': '74',
  'title': 'Klaus',
  'runtime': '1h 36m',
  'year': '2019',
  'rating': '8.2',
  'votes': '222K'},
 {'movie_id': 'tt1027238',
  'rank': '75',
  'title': 'The Father',
  'runtime': '1h 37m',
  'year': '2020',
  'rating': '8.2',
  'votes': '221K'},
 {'movie_id': 'tt1560220',
  'rank': '76',
  'title': 'Zombieland: Double Tap',
  'runtime': '1h 39m',
  'year': '2019',
  'rating': '6.7',
  'votes': '220K'},
 {'movie_id': 'tt1028856',
  'rank': '77',
  'title': 'Another Round',
  'runtime': '1h 57m',
  'year': '2020',
  'rating': '7.7',
  'votes': '220K'},
 {'movie_id': 'tt2873282',
  'rank': '78',
  'title': 'Red Sparrow',
  'runtime': '2h 20m',
  'year': '2018',
  'rating': '6.6',
  'votes': '215K'},
 {'movie_id': 'tt1213641',
  'rank': '79',
  'title': 'First Man',
  'runtime': '2h 21m',
  'year': '2018',
  'rating': '7.3',
  'votes': '213K'},
 {'movie_id': 'tt4520988',
  'rank': '80',
  'title': 'Frozen II',
  'runtime': '1h 43m',
  'year': '2019',
  'rating': '6.8',
  'votes': '213K'},
 {'movie_id': 'tt6450804',
  'rank': '81',
  'title': 'Terminator: Dark Fate',
  'runtime': '2h 8m',
  'year': '2019',
  'rating': '6.2',
  'votes': '208K'},
 {'movie_id': 'tt8106534',
  'rank': '82',
  'title': '6 Underground',
  'runtime': '2h 8m',
  'year': '2019',
  'rating': '6.1',
  'votes': '208K'},
 {'movie_id': 'tt9484998',
  'rank': '83',
  'title': 'Palm Springs',
  'runtime': '1h 30m',
  'year': '2020',
  'rating': '7.4',
  'votes': '207K'},
 {'movie_id': 'tt7556122',
  'rank': '84',
  'title': 'The Old Guard',
  'runtime': '2h 5m',
  'year': '2020',
  'rating': '6.7',
  'votes': '207K'},
 {'movie_id': 'tt2066051',
  'rank': '85',
  'title': 'Rocketman',
  'runtime': '2h 1m',
  'year': '2019',
  'rating': '7.3',
  'votes': '206K'},
 {'movie_id': 'tt5104604',
  'rank': '86',
  'title': 'Isle of Dogs',
  'runtime': '1h 41m',
  'year': '2018',
  'rating': '7.8',
  'votes': '206K'},
 {'movie_id': 'tt3104988',
  'rank': '87',
  'title': 'Crazy Rich Asians',
  'runtime': '2h',
  'year': '2018',
  'rating': '6.9',
  'votes': '205K'},
 {'movie_id': 'tt4701182',
  'rank': '88',
  'title': 'Bumblebee',
  'runtime': '1h 54m',
  'year': '2018',
  'rating': '6.7',
  'votes': '204K'},
 {'movie_id': 'tt1070874',
  'rank': '89',
  'title': 'The Trial of the Chicago 7',
  'runtime': '2h 9m',
  'year': '2020',
  'rating': '7.7',
  'votes': '203K'},
 {'movie_id': 'tt5848272',
  'rank': '90',
  'title': 'Ralph Breaks the Internet',
  'runtime': '1h 52m',
  'year': '2018',
  'rating': '7.0',
  'votes': '200K'},
 {'movie_id': 'tt2231461',
  'rank': '91',
  'title': 'Rampage',
  'runtime': '1h 47m',
  'year': '2018',
  'rating': '6.1',
  'votes': '198K'},
 {'movie_id': 'tt9770150',
  'rank': '92',
  'title': 'Nomadland',
  'runtime': '1h 47m',
  'year': '2020',
  'rating': '7.3',
  'votes': '197K'},
 {'movie_id': 'tt1502397',
  'rank': '93',
  'title': 'Bad Boys for Life',
  'runtime': '2h 4m',
  'year': '2020',
  'rating': '6.5',
  'votes': '194K'},
 {'movie_id': 'tt5884052',
  'rank': '94',
  'title': 'Pokémon: Detective Pikachu',
  'runtime': '1h 44m',
  'year': '2019',
  'rating': '6.5',
  'votes': '194K'},
 {'movie_id': 'tt5814060',
  'rank': '95',
  'title': 'The Nun',
  'runtime': '1h 36m',
  'year': '2018',
  'rating': '5.4',
  'votes': '191K'},
 {'movie_id': 'tt7668870',
  'rank': '96',
  'title': 'Searching',
  'runtime': '1h 42m',
  'year': '2018',
  'rating': '7.6',
  'votes': '190K'},
 {'movie_id': 'tt7040874',
  'rank': '97',
  'title': 'A Simple Favor',
  'runtime': '1h 57m',
  'year': '2018',
  'rating': '6.7',
  'votes': '188K'},
 {'movie_id': 'tt3794354',
  'rank': '98',
  'title': 'Sonic the Hedgehog',
  'runtime': '1h 39m',
  'year': '2020',
  'rating': '6.5',
  'votes': '187K'},
 {'movie_id': 'tt1618434',
  'rank': '99',
  'title': 'Murder Mystery',
  'runtime': '1h 37m',
  'year': '2019',
  'rating': '6.1',
  'votes': '185K'},
 {'movie_id': 'tt5052474',
  'rank': '100',
  'title': 'Sicario: Day of the Soldado',
  'runtime': '2h 2m',
  'year': '2018',
  'rating': '7.1',
  'votes': '185K'},
 {'movie_id': 'tt4500922',
  'rank': '101',
  'title': 'Maze Runner: The Death Cure',
  'runtime': '2h 23m',
  'year': '2018',
  'rating': '6.3',
  'votes': '184K'},
 {'movie_id': 'tt1502407',
  'rank': '102',
  'title': 'Halloween',
  'runtime': '1h 46m',
  'year': '2018',
  'rating': '6.5',
  'votes': '184K'},
 {'movie_id': 'tt7146812',
  'rank': '103',
  'title': 'Onward',
  'runtime': '1h 42m',
  'year': '2020',
  'rating': '7.4',
  'votes': '183K'},
 {'movie_id': 'tt8079248',
  'rank': '104',
  'title': 'Yesterday',
  'runtime': '1h 56m',
  'year': '2019',
  'rating': '6.8',
  'votes': '181K'},
 {'movie_id': 'tt6412452',
  'rank': '105',
  'title': 'The Ballad of Buster Scruggs',
  'runtime': '2h 13m',
  'year': '2018',
  'rating': '7.2',
  'votes': '180K'},
 {'movie_id': 'tt6155172',
  'rank': '106',
  'title': 'Roma',
  'runtime': '2h 15m',
  'year': '2018',
  'rating': '7.6',
  'votes': '176K'},
 {'movie_id': 'tt6628394',
  'rank': '107',
  'title': 'Bad Times at the El Royale',
  'runtime': '2h 21m',
  'year': '2018',
  'rating': '7.1',
  'votes': '176K'},
 {'movie_id': 'tt2386490',
  'rank': '108',
  'title': 'How to Train Your Dragon: The Hidden World',
  'runtime': '1h 44m',
  'year': '2019',
  'rating': '7.4',
  'votes': '173K'},
 {'movie_id': 'tt6266538',
  'rank': '109',
  'title': 'Vice',
  'runtime': '2h 12m',
  'year': '2018',
  'rating': '7.2',
  'votes': '172K'},
 {'movie_id': 'tt7984766',
  'rank': '110',
  'title': 'The King',
  'runtime': '2h 20m',
  'year': '2019',
  'rating': '7.3',
  'votes': '171K'},
 {'movie_id': 'tt6343314',
  'rank': '111',
  'title': 'Creed II',
  'runtime': '2h 10m',
  'year': '2018',
  'rating': '7.1',
  'votes': '167K'},
 {'movie_id': 'tt4566758',
  'rank': '112',
  'title': 'Mulan',
  'runtime': '1h 55m',
  'year': '2020',
  'rating': '5.8',
  'votes': '166K'},
 {'movie_id': 'tt7959026',
  'rank': '113',
  'title': 'The Mule',
  'runtime': '1h 56m',
  'year': '2018',
  'rating': '7.0',
  'votes': '166K'},
 {'movie_id': 'tt7395114',
  'rank': '114',
  'title': 'The Devil All the Time',
  'runtime': '2h 18m',
  'year': '2020',
  'rating': '7.1',
  'votes': '165K'},
 {'movie_id': 'tt5363618',
  'rank': '115',
  'title': 'Sound of Metal',
  'runtime': '2h',
  'year': '2019',
  'rating': '7.7',
  'votes': '164K'},
 {'movie_id': 'tt1314396',
  'rank': '116',
  'title': 'Borat Subsequent Moviefilm',
  'runtime': '1h 35m',
  'year': '2020',
  'rating': '6.6',
  'votes': '162K'},
 {'movie_id': 'tt2854926',
  'rank': '117',
  'title': 'Tag',
  'runtime': '1h 40m',
  'year': '2018',
  'rating': '6.5',
  'votes': '159K'},
 {'movie_id': 'tt3829266',
  'rank': '118',
  'title': 'The Predator',
  'runtime': '1h 47m',
  'year': '2018',
  'rating': '5.3',
  'votes': '158K'},
 {'movie_id': 'tt1488606',
  'rank': '119',
  'title': 'Triple Frontier',
  'runtime': '2h 5m',
  'year': '2019',
  'rating': '6.5',
  'votes': '158K'},
 {'movie_id': 'tt2283336',
  'rank': '120',
  'title': 'Men in Black: International',
  'runtime': '1h 54m',
  'year': '2019',
  'rating': '5.6',
  'votes': '158K'},
 {'movie_id': 'tt2222042',
  'rank': '121',
  'title': 'Love and Monsters',
  'runtime': '1h 49m',
  'year': '2020',
  'rating': '6.9',
  'votes': '156K'},
 {'movie_id': 'tt9893250',
  'rank': '122',
  'title': 'I Care a Lot',
  'runtime': '1h 58m',
  'year': '2020',
  'rating': '6.4',
  'votes': '156K'},
 {'movie_id': 'tt5886046',
  'rank': '123',
  'title': 'Escape Room',
  'runtime': '1h 39m',
  'year': '2019',
  'rating': '6.4',
  'votes': '156K'},
 {'movie_id': 'tt7737786',
  'rank': '124',
  'title': 'Greenland',
  'runtime': '1h 59m',
  'year': '2020',
  'rating': '6.4',
  'votes': '151K'},
 {'movie_id': 'tt1571234',
  'rank': '125',
  'title': 'Mortal Engines',
  'runtime': '2h 8m',
  'year': '2018',
  'rating': '6.1',
  'votes': '151K'},
 {'movie_id': 'tt1259528',
  'rank': '126',
  'title': 'Den of Thieves',
  'runtime': '2h 20m',
  'year': '2018',
  'rating': '7.0',
  'votes': '150K'},
 {'movie_id': 'tt8244784',
  'rank': '127',
  'title': 'The Hunt',
  'runtime': '1h 30m',
  'year': '2020',
  'rating': '6.6',
  'votes': '149K'},
 {'movie_id': 'tt8404614',
  'rank': '128',
  'title': 'The Two Popes',
  'runtime': '2h 5m',
  'year': '2019',
  'rating': '7.6',
  'votes': '144K'},
 {'movie_id': 'tt5758778',
  'rank': '129',
  'title': 'Skyscraper',
  'runtime': '1h 42m',
  'year': '2018',
  'rating': '5.8',
  'votes': '143K'},
 {'movie_id': 'tt9495224',
  'rank': '130',
  'title': 'Black Mirror: Bandersnatch',
  'runtime': '1h 30m',
  'year': '2018',
  'rating': '7.1',
  'votes': '142K'},
 {'movie_id': 'tt1489887',
  'rank': '131',
  'title': 'Booksmart',
  'runtime': '1h 42m',

In [4]:
# to convert the movies list of dics to dataframe
df_movies = pd.DataFrame(Movies_list)
df_movies

,movie_id,rank,title,runtime,year,rating,votes
0,tt7286456,1,Joker,2h 2m,2019,8.3,1.7M
1,tt4154796,2,Avengers: Endgame,3h 1m,2019,8.4,1.4M
2,tt4154756,3,Avengers: Infinity War,2h 29m,2018,8.4,1.3M
3,tt6751668,4,Parasite,2h 12m,2019,8.5,1.1M
4,tt7131622,5,Once Upon a Time... in Hollywood,2h 41m,2019,7.6,936K
...,...,...,...,...,...,...,...
495,tt8385474,496,A Dog's Journey,1h 49m,2019,7.4,32K
496,tt6587640,497,Trolls World Tour,1h 31m,2020,6.1,32K
497,tt2126357,498,Second Act,1h 43m,2018,5.8,32K
498,tt3612126,499,The Grudge,1h 34m,2019,4.4,32K
499,tt7218518,500,Pad Man,2h 20m,2018,7.8,32K

***
#  To export the colleted movies to IMDb_TopVoted.csv file.

In [5]:
df_movies.to_csv('IMDb_TopVoted.csv', index = False)

# Importing the given dataset "Movies.csv" to Pandas DataFrame called df1

In [6]:
# Importing the csv file to df1 and print the df1.
df1 = pd.read_csv('Movies.csv', encoding='ISO-8859-1')
df1

,movie_id,originalTitle,description,ratingCategory,genres
0,tt7286456,Joker,"During the 1980s, a failed stand-up comedian i...",R,"Crime,Drama,Thriller"
1,tt4154796,Avengers: Endgame,After the devastating events of Avengers: Infi...,PG-13,"Action,Adventure,Drama"
2,tt4154756,Avengers: Infinity War,The Avengers and their allies must be willing ...,PG-13,"Action,Adventure,Sci-Fi"
3,tt6751668,Parasite,Greed and class discrimination threaten the ne...,R,"Drama,Thriller"
4,tt1825683,Black Panther,"T'Challa, heir to the hidden but advanced king...",PG-13,"Action,Adventure,Sci-Fi"
...,...,...,...,...,...
495,tt9072352,Relic,"A daughter, mother and grandmother are haunted...",R,"Drama,Horror,Mystery"
496,tt1006569,Episode dated 9 August 2005,Successful author Veronica Henley finds hersel...,R,News
497,tt8652728,Waves,Traces the journey of a suburban family - led ...,R,"Drama,Romance,Sport"
498,tt7748244,Mortal World,Mermer Family lives a double life working at t...,R,"Action,Comedy,Crime"
499,tt6768578,Dogman,A timid dog groomer living in a poor suburb se...,Not Rated,"Crime,Drama,Thriller"

# Import the scraped data from the IMDb_TopVoted.csv file to Pandas DataFrame called df2

In [7]:
# You need to import the collected dataset "IMDb_TopVoted.csv" and print the df2.
# To handel Latin characters that may contained in the csv file
# with no issue, use  encoding= "ISO-8859-1" with the pd.read_csv()
# Example: df1 = pd.read_csv('thefilename.csv', encoding= "ISO-8859-1") 
# Using encoding= "ISO-8859-1" will avoid Unicode-Decode-Errors.
df2 = pd.read_csv('IMDb_TopVoted.csv', encoding='ISO-8859-1')
df2

,movie_id,rank,title,runtime,year,rating,votes
0,tt7286456,1,Joker,2h 2m,2019,8.3,1.7M
1,tt4154796,2,Avengers: Endgame,3h 1m,2019,8.4,1.4M
2,tt4154756,3,Avengers: Infinity War,2h 29m,2018,8.4,1.3M
3,tt6751668,4,Parasite,2h 12m,2019,8.5,1.1M
4,tt7131622,5,Once Upon a Time... in Hollywood,2h 41m,2019,7.6,936K
...,...,...,...,...,...,...,...
495,tt8385474,496,A Dog's Journey,1h 49m,2019,7.4,32K
496,tt6587640,497,Trolls World Tour,1h 31m,2020,6.1,32K
497,tt2126357,498,Second Act,1h 43m,2018,5.8,32K
498,tt3612126,499,The Grudge,1h 34m,2019,4.4,32K
499,tt7218518,500,Pad Man,2h 20m,2018,7.8,32K

# Data cleansing and transformation for df2.

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  500 non-null    object
 1   rank      500 non-null    int64
 2   title     500 non-null    object
 3   runtime   500 non-null    object
 4   year      500 non-null    int64
 5   rating    500 non-null    float64
 6   votes     500 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 27.5+ KB

In [9]:
# Cleaning and tranforming df2
 # rank, year, and votes should have a numeric integer data type.
 # runtime column should be renamed to runtimeMinutes and the value should be in minutes, 
 # for example: 2h 2m should be 122
# Convert rank to integer (remove any periods)
df2['rank'] = df2['rank'].astype(str).str.replace('.', '').astype(int)

# Convert year to integer
df2['year'] = df2['year'].astype(int)

# Convert votes to integer (handle formats like "1.4M", "938K", etc.)
def convert_votes(vote_str):
    vote_str = str(vote_str).strip().upper()
    if 'M' in vote_str:
        return int(float(vote_str.replace('M', '')) * 1_000_000)
    elif 'K' in vote_str:
        return int(float(vote_str.replace('K', '')) * 1_000)
    else:
        return int(vote_str.replace(',', ''))

df2['votes'] = df2['votes'].apply(convert_votes)

# Convert runtime to minutes and rename to runtimeMinutes
def convert_runtime(runtime_str):
    runtime_str = str(runtime_str)
    hours = 0
    minutes = 0
    if 'h' in runtime_str:
        hours = int(runtime_str.split('h')[0].strip())
        remainder = runtime_str.split('h')[1]
        if 'm' in remainder:
            minutes = int(remainder.replace('m', '').strip())
    elif 'm' in runtime_str:
        minutes = int(runtime_str.replace('m', '').strip())
    return hours * 60 + minutes

df2['runtimeMinutes'] = df2['runtime'].apply(convert_runtime)
df2 = df2.drop(columns=['runtime'])  # Drop the original runtime column

# Convert rating to float
df2['rating'] = df2['rating'].astype(float)

df2.info()
df2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_id        500 non-null    object
 1   rank            500 non-null    int64
 2   title           500 non-null    object
 3   year            500 non-null    int64
 4   rating          500 non-null    float64
 5   votes           500 non-null    int64
 6   runtimeMinutes  500 non-null    int64
dtypes: float64(1), int64(4), object(2)
memory usage: 27.5+ KB

,movie_id,rank,title,year,rating,votes,runtimeMinutes
0,tt7286456,1,Joker,2019,8.3,1700000,122
1,tt4154796,2,Avengers: Endgame,2019,8.4,1400000,181
2,tt4154756,3,Avengers: Infinity War,2018,8.4,1300000,149
3,tt6751668,4,Parasite,2019,8.5,1100000,132
4,tt7131622,5,Once Upon a Time... in Hollywood,2019,7.6,936000,161
...,...,...,...,...,...,...,...
495,tt8385474,496,A Dog's Journey,2019,7.4,32000,109
496,tt6587640,497,Trolls World Tour,2020,6.1,32000,91
497,tt2126357,498,Second Act,2018,5.8,32000,103
498,tt3612126,499,The Grudge,2019,4.4,32000,94
499,tt7218518,500,Pad Man,2018,7.8,32000,140

# 	Enrich the given dataset (df1) by merging it to the scraped data (df2).

In [10]:
# Merege the two dataframes to one dataframe called df.
df = pd.merge(df1, df2, on='movie_id', how='inner')
df

,movie_id,originalTitle,description,ratingCategory,genres,rank,title,year,rating,votes,runtimeMinutes
0,tt7286456,Joker,"During the 1980s, a failed stand-up comedian i...",R,"Crime,Drama,Thriller",1,Joker,2019,8.3,1700000,122
1,tt4154796,Avengers: Endgame,After the devastating events of Avengers: Infi...,PG-13,"Action,Adventure,Drama",2,Avengers: Endgame,2019,8.4,1400000,181
2,tt4154756,Avengers: Infinity War,The Avengers and their allies must be willing ...,PG-13,"Action,Adventure,Sci-Fi",3,Avengers: Infinity War,2018,8.4,1300000,149
3,tt6751668,Parasite,Greed and class discrimination threaten the ne...,R,"Drama,Thriller",4,Parasite,2019,8.5,1100000,132
4,tt1825683,Black Panther,"T'Challa, heir to the hidden but advanced king...",PG-13,"Action,Adventure,Sci-Fi",6,Black Panther,2018,7.3,893000,134
...,...,...,...,...,...,...,...,...,...,...,...
487,tt9252468,Mosul,A police unit from Mosul fight to liberate the...,TV-MA,"Action,Drama,Thriller",493,Mosul,2019,7.1,33000,101
488,tt3152592,Scoob!,Scooby and the gang face their most challengin...,PG,"Adventure,Animation,Comedy",494,Scoob!,2020,5.6,32000,93
489,tt9072352,Relic,"A daughter, mother and grandmother are haunted...",R,"Drama,Horror,Mystery",492,Relic,2020,6.0,33000,89
490,tt8652728,Waves,Traces the journey of a suburban family - led ...,R,"Drama,Romance,Sport",461,Waves,2019,7.5,36000,135
491,tt7748244,Mortal World,Mermer Family lives a double life working at t...,R,"Action,Comedy,Crime",476,Mortal World,2018,7.6,34000,107

# Rearrange the dataset fields to be listed in the following order: 
movie_id , rank , title ,  originalTitle ,  description ,
          year ,  votes , rating ,  runtimeMinutes ,  ratingCategory ,  genres

In [11]:
# Rearrange the dataset fields.
df = df[['movie_id', 'rank', 'title', 'originalTitle', 'description', 
         'year', 'votes', 'rating', 'runtimeMinutes', 'ratingCategory', 'genres']]
df

,movie_id,rank,title,originalTitle,description,year,votes,rating,runtimeMinutes,ratingCategory,genres
0,tt7286456,1,Joker,Joker,"During the 1980s, a failed stand-up comedian i...",2019,1700000,8.3,122,R,"Crime,Drama,Thriller"
1,tt4154796,2,Avengers: Endgame,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,1400000,8.4,181,PG-13,"Action,Adventure,Drama"
2,tt4154756,3,Avengers: Infinity War,Avengers: Infinity War,The Avengers and their allies must be willing ...,2018,1300000,8.4,149,PG-13,"Action,Adventure,Sci-Fi"
3,tt6751668,4,Parasite,Parasite,Greed and class discrimination threaten the ne...,2019,1100000,8.5,132,R,"Drama,Thriller"
4,tt1825683,6,Black Panther,Black Panther,"T'Challa, heir to the hidden but advanced king...",2018,893000,7.3,134,PG-13,"Action,Adventure,Sci-Fi"
...,...,...,...,...,...,...,...,...,...,...,...
487,tt9252468,493,Mosul,Mosul,A police unit from Mosul fight to liberate the...,2019,33000,7.1,101,TV-MA,"Action,Drama,Thriller"
488,tt3152592,494,Scoob!,Scoob!,Scooby and the gang face their most challengin...,2020,32000,5.6,93,PG,"Adventure,Animation,Comedy"
489,tt9072352,492,Relic,Relic,"A daughter, mother and grandmother are haunted...",2020,33000,6.0,89,R,"Drama,Horror,Mystery"
490,tt8652728,461,Waves,Waves,Traces the journey of a suburban family - led ...,2019,36000,7.5,135,R,"Drama,Romance,Sport"
491,tt7748244,476,Mortal World,Mortal World,Mermer Family lives a double life working at t...,2018,34000,7.6,107,R,"Action,Comedy,Crime"

# Export the enriched dataset to a CSV file:

In [12]:
# Use the following naming convention: 
#  Project_3_PartA_Lastname.csv
df.to_csv('Project_3_Part_A_Group11.csv', index=False)